### ISSUE TITLE
Unit-tests are failing after PR# 1903 merge on master branch

### ISSUE THREAD

**Issue by rameshthoomu** [hyperledger-archives/fabric#1965]
## Description

`core/rest/rest_api_test.go` unit-test is failing after PR#1903 merge. Below is the error message observed in the log file.

commit#1e0fc31
Reference PR#(1903)
Date: 06/23/2016

```
core/rest/rest_api_test.go:124: cannot use new(mockDevops) (type *mockDevops) as type "github.com/hyperledger/fabric/protos".DevopsServer in assignment:
    *mockDevops does not implement "github.com/hyperledger/fabric/protos".DevopsServer (missing EXP_ExecuteWithBinding method)

FAIL    github.com/hyperledger/fabric/core/rest [build failed]
```
## Describe How to Reproduce

Pull commit# 1e0fc31 and execute make unit-test 
Travis and Jenkin Builds are failing: Below are the failed builds# 1265,1267,1269 (Travis Builds) & https://jenkins.hyperledger.org/view/fabric/job/fabric-github-merge-x86_64/128/console (Jenkins)

**Comment by srderson** [comment]
PR #1903 was broken due to PR #1923 being merged first.
